apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      tolerations:
        - operator: Exists
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: agent
          image: {{ include "meridian.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.agent.image.repository "tag" .Values.agent.image.tag) }}
          env:
            - name: MERIDIAN_AGENT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
              add: ["NET_RAW"]
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
            - name: buffer
              mountPath: /var/lib/meridian/buffer
      volumes:
        - name: buffer
          emptyDir:
            sizeLimit: {{ .Values.agent.bufferSizeLimit }}
