apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.controller.service.port }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1100
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: {{ include "meridian.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.controller.image.repository "tag" .Values.controller.image.tag) }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.controller.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.controller.service.port }}, scheme: HTTPS }
          readinessProbe:
            httpGet: { path: /readyz, port: {{ .Values.controller.service.port }}, scheme: HTTPS }
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
