{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.1
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          ports:
            - containerPort: 3000
{{- end }}
