{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
