apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meridian
resources:
  - ../../base
namePrefix: prod-
labels:
  - pairs:
      app.kubernetes.io/environment: prod
patches:
  - target:
      kind: Deployment
      name: meridian-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
